name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        python3 -m pip install pandas lxml
        python3 -c 'import sys, pandas as pd; pd.read_html("https://theodorepayne.org/plants-and-seeds/nursery/inventory/", header=0)[0].to_csv(sys.stdout, sep="\t", index=False)' > data.tsv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
