name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '26 14 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        python3 -m pip install pandas lxml requests
        python3 -c 'import sys, pandas as pd, requests; html = requests.get("https://theodorepayne.org/plants-and-seeds/nursery/inventory/", headers={'User-agent': 'webrobot@cordaz.com'}).text; pd.read_html(html, header=)[0].to_csv("data.csv", index=False)'
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
